apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
  namespace: <namespace>
spec:
  hard:
    configmaps: "10"
    persistentvolumeclaims: "4"
    replicationcontrollers: "20"
    secrets: "10"
    services: "10"
    service.loadbalancers: "2"
