apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
  initContainers:
    - name: init-myservice
      image: myimage
      command: ['sh', '-c', 'git clone <some-repo>; done;'']