apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: myapp
  namespace: default
spec:
  secretName: myapp-tls-prod
  issuerRef:
    name: myapp-letsncrypt-prod
  commonName: myapp.ibaset.com
  #dnsNames:
  #- www.myapp.ibaset.com
  acme:
    config:
      - http01:
          ingress: myapp
        domains:
          - myapp.ibaset.com
        #- www.myapp.ibaset.com
