apiVersion: v1
kind: Deployment
metadata:
  name: notification
  namespace: default
  labels:
    app.kubernetes.io/managed-by: iivanov
spec:
  replicas: 1
  selector:
    app.kubernetes.io/name: notification
  template:
    metadata:
      labels:
        app.kubernetes.io/name: notification
    spec:
      containers:
        - name: notification
          image: {{ .Values.imageRegistry }}/solui:{{ .Values.dockerTag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - containerPort: 5432
          env:
            - name: DATABASE_STORAGE
              value: {{ default "minio" .Values.storage }}