---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-app
  namespace: demo
  labels:
    app: python-web-app
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.python-web-app: semver:~1.0.0
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: python-web-app
  template:
    metadata:
      labels:
        app: python-web-app
    spec:
      containers:
        - name: python-web-app
          image: wardviaene/python-web-app:1.0.2
          ports:
            - name: python-web-app-port
              containerPort: 8008
---
apiVersion: v1
kind: Service
metadata:
  name: python-web-app
  namespace: demo
spec:
  ports:
    - port: 8008
      targetPort: nodejs-port
      protocol: TCP
  selector:
    app: python-web-app
  type: NodePort
