apiVersion: apps/v1
kind: Deployment
metadata:
  name: awesome-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: app-label
    spec:
      containers:
        - name: app-api
          image: docker.ambrygen.com/bstr/spliceai-api/api
          # command: ["python", "app.py"]
          ports:
            - name: app-port
              # containerPort: 8000
          env:
            # Secrets Example
            - name: MYSQL_HOST
              value: database-service
            - name: MYSQL_USER
              value: root
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: rootPassword
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: database
            # ConfigMap Example
            - name: DRIVER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: driver
  selector:
    matchLabels:
      app: awesome-app
