apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: app-demo
          image: <repo/app-demo>
          command: ["python", "app.py"]
          ports:
          - name: python-port
            containerPort: 3000
          env: 
            - name: MYSQL_HOST
              value: database-service
            - name: MYSQL_USER
              value: root
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: rootPassword
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: database

              

  selector:
    matchLabels:
      app: myapp
